baseURL = "https://pm8s.io/"
languageCode = "en-us"
title = "PlayM8s"
sectionPagesMenu = "primary"

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = "PlayM8s"
    languageName = "English"
    weight = 10

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]
  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font
  description     = "PlayM8s"

[params.docs]
  intLinkTooltip = true
  extLinkNewTab  = true
  prism          = true 
  prismTheme     = "lucario"
  title          = "pm8s.io"
  logoLinkURL    = "https://pm8s.io/docs"
  darkMode       = true
  themeColor     = "blue"

[params.footer]
  copyright = "Attribution-NonCommercial-ShareAlike 4.0 International"

[params.social]
  github = "playm8s"

[HTTPCache]
  [HTTPCache.cache]
    [HTTPCache.cache.for]
      excludes = ['**']
      includes = []
